// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package mathHelper

func MaxInt(x, y int) int {
	if x > y {
		return x
	}

	return y
}

func MinInt(x, y int) int {
	if x < y {
		return x
	}

	return y
}

func ClampInt(min, max, val int) int {
	return MinInt(MaxInt(min, val), max)
}

func MaxInt32(x, y int32) int32 {
	if x > y {
		return x
	}

	return y
}

func MinInt32(x, y int32) int32 {
	if x < y {
		return x
	}

	return y
}

func ClampInt32(min, max, val int32) int32 {
	return MinInt32(MaxInt32(min, val), max)
}

func MaxInt64(x, y int64) int64 {
	if x > y {
		return x
	}

	return y
}

func MinInt64(x, y int64) int64 {
	if x < y {
		return x
	}

	return y
}

func ClampInt64(min, max, val int64) int64 {
	return MinInt64(MaxInt64(min, val), max)
}

func MaxUint(x, y uint) uint {
	if x > y {
		return x
	}

	return y
}

func MinUint(x, y uint) uint {
	if x < y {
		return x
	}

	return y
}

func ClampUint(min, max, val uint) uint {
	return MinUint(MaxUint(min, val), max)
}

func MaxUint32(x, y uint32) uint32 {
	if x > y {
		return x
	}

	return y
}

func MinUint32(x, y uint32) uint32 {
	if x < y {
		return x
	}

	return y
}

func ClampUint32(min, max, val uint32) uint32 {
	return MinUint32(MaxUint32(min, val), max)
}

func MaxUint64(x, y uint64) uint64 {
	if x > y {
		return x
	}

	return y
}

func MinUint64(x, y uint64) uint64 {
	if x < y {
		return x
	}

	return y
}

func ClampUint64(min, max, val uint64) uint64 {
	return MinUint64(MaxUint64(min, val), max)
}

func MaxFloat32(x, y float32) float32 {
	if x > y {
		return x
	}

	return y
}

func MinFloat32(x, y float32) float32 {
	if x < y {
		return x
	}

	return y
}

func ClampFloat32(min, max, val float32) float32 {
	return MinFloat32(MaxFloat32(min, val), max)
}

func MaxFloat64(x, y float64) float64 {
	if x > y {
		return x
	}

	return y
}

func MinFloat64(x, y float64) float64 {
	if x < y {
		return x
	}

	return y
}

func ClampFloat64(min, max, val float64) float64 {
	return MinFloat64(MaxFloat64(min, val), max)
}
